### ISSUE TITLE
[JOSS] Missing note on community guidelines for contribution

### ISSUE THREAD

**Issue by gknapp1** [usnistgov/imppy3d#7]
While you have community guidelines on how to get support for issues, there are no guidelines for how third parties can contribute to this project (see [JOSS Review Criteria: Community Guidelines](https://joss.readthedocs.io/en/latest/review_criteria.html#community-guidelines)). Please address this in your readme.

Linkback: https://github.com/openjournals/joss-reviews/issues/7405

**Comment by NM0ser** [comment]
Thanks, I think we have these guidelines clearer now in the updated ReadMe, but let me know if we should add more detail.
